# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\"\x17\n\x03Key\x12\x10\n\x08key_name\x18\x01 \x01(\t\"\x1b\n\x05Value\x12\x12\n\nvalue_name\x18\x01 \x01(\t\"4\n\x08KeyValue\x12\x11\n\x03key\x18\x01 \x01(\x0b\x32\x04.Key\x12\x15\n\x05value\x18\x02 \x01(\x0b\x32\x06.Value\"\x18\n\x06Status\x12\x0e\n\x06result\x18\x01 \x01(\t\"-\n\x05\x44\x65que\x12\x16\n\x08key_name\x18\x01 \x01(\x0b\x32\x04.Key\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\t\";\n\tListRange\x12\x11\n\x03key\x18\x01 \x01(\x0b\x32\x04.Key\x12\r\n\x05start\x18\x02 \x01(\x05\x12\x0c\n\x04stop\x18\x03 \x01(\x05\">\n\x0bResponseVal\x12\x0f\n\x05noval\x18\x01 \x01(\x08H\x00\x12\x17\n\x05value\x18\x02 \x01(\x0b\x32\x06.ValueH\x00\x42\x05\n\x03res2\xb0\x01\n\x08KeyStore\x12\x19\n\x03Set\x12\t.KeyValue\x1a\x07.Status\x12\x19\n\x03Get\x12\x04.Key\x1a\x0c.ResponseVal\x12\x17\n\x06\x44\x65lete\x12\x04.Key\x1a\x07.Status\x12\x1b\n\x05LPush\x12\t.KeyValue\x1a\x07.Status\x12\x1c\n\x06LRange\x12\n.ListRange\x1a\x06.Deque\x12\x1a\n\x04LPop\x12\x04.Key\x1a\x0c.ResponseValb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEY']._serialized_start=16
  _globals['_KEY']._serialized_end=39
  _globals['_VALUE']._serialized_start=41
  _globals['_VALUE']._serialized_end=68
  _globals['_KEYVALUE']._serialized_start=70
  _globals['_KEYVALUE']._serialized_end=122
  _globals['_STATUS']._serialized_start=124
  _globals['_STATUS']._serialized_end=148
  _globals['_DEQUE']._serialized_start=150
  _globals['_DEQUE']._serialized_end=195
  _globals['_LISTRANGE']._serialized_start=197
  _globals['_LISTRANGE']._serialized_end=256
  _globals['_RESPONSEVAL']._serialized_start=258
  _globals['_RESPONSEVAL']._serialized_end=320
  _globals['_KEYSTORE']._serialized_start=323
  _globals['_KEYSTORE']._serialized_end=499
# @@protoc_insertion_point(module_scope)
