# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import schema_pb2 as schema__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in schema_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KeyStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Set = channel.unary_unary(
                '/KeyStore/Set',
                request_serializer=schema__pb2.KeyValue.SerializeToString,
                response_deserializer=schema__pb2.Status.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/KeyStore/Get',
                request_serializer=schema__pb2.Key.SerializeToString,
                response_deserializer=schema__pb2.ResponseVal.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/KeyStore/Delete',
                request_serializer=schema__pb2.Key.SerializeToString,
                response_deserializer=schema__pb2.Status.FromString,
                _registered_method=True)
        self.LPush = channel.unary_unary(
                '/KeyStore/LPush',
                request_serializer=schema__pb2.KeyValue.SerializeToString,
                response_deserializer=schema__pb2.Status.FromString,
                _registered_method=True)
        self.LRange = channel.unary_unary(
                '/KeyStore/LRange',
                request_serializer=schema__pb2.ListRange.SerializeToString,
                response_deserializer=schema__pb2.Deque.FromString,
                _registered_method=True)
        self.LPop = channel.unary_unary(
                '/KeyStore/LPop',
                request_serializer=schema__pb2.Key.SerializeToString,
                response_deserializer=schema__pb2.ResponseVal.FromString,
                _registered_method=True)


class KeyStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LPush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LPop(self, request, context):
        """rpc ListAll(Key) returns (stream KeyValue);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=schema__pb2.KeyValue.FromString,
                    response_serializer=schema__pb2.Status.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=schema__pb2.Key.FromString,
                    response_serializer=schema__pb2.ResponseVal.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=schema__pb2.Key.FromString,
                    response_serializer=schema__pb2.Status.SerializeToString,
            ),
            'LPush': grpc.unary_unary_rpc_method_handler(
                    servicer.LPush,
                    request_deserializer=schema__pb2.KeyValue.FromString,
                    response_serializer=schema__pb2.Status.SerializeToString,
            ),
            'LRange': grpc.unary_unary_rpc_method_handler(
                    servicer.LRange,
                    request_deserializer=schema__pb2.ListRange.FromString,
                    response_serializer=schema__pb2.Deque.SerializeToString,
            ),
            'LPop': grpc.unary_unary_rpc_method_handler(
                    servicer.LPop,
                    request_deserializer=schema__pb2.Key.FromString,
                    response_serializer=schema__pb2.ResponseVal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KeyStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('KeyStore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeyStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KeyStore/Set',
            schema__pb2.KeyValue.SerializeToString,
            schema__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KeyStore/Get',
            schema__pb2.Key.SerializeToString,
            schema__pb2.ResponseVal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KeyStore/Delete',
            schema__pb2.Key.SerializeToString,
            schema__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LPush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KeyStore/LPush',
            schema__pb2.KeyValue.SerializeToString,
            schema__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KeyStore/LRange',
            schema__pb2.ListRange.SerializeToString,
            schema__pb2.Deque.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LPop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KeyStore/LPop',
            schema__pb2.Key.SerializeToString,
            schema__pb2.ResponseVal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
